### ISSUE TITLE
conflict with adb idea

### ISSUE THREAD

**Issue by wilsonssss** [whunmr/emacsIDEAs#12]
os: osx 10.11.6
android studio: 2.2 beta
emacsIdeas: 1.3.6
adb idea:[1.2.7](https://github.com/pbreault/adb-idea)

after upgrade emacsIdeas from 1.3.2 to 1.3.6,  adb idea will crash, 1.3.2 performs good.

**Comment by whunmr** [comment]
@wilsonssss , thanks for your report.

I found emacsIDEAs can not run on a default installation of Android Studio 2.1.3, because dependency on JDK1.7.
I made a new version of emacsIDEAs 1.3.7, to fix the can not run problem.

Per this #12 issue, while I setup the test environment of Android Studio 2.2 beta, Could you please provide some crash log, if possible?

**Comment by whunmr** [comment]
works on my computer.   but I didn't have an Android project opened.

os: osx 10.11.6
android studio: 2.2 beta
emacsIdeas: 1.3.7
adb idea:1.2.7

**Comment by whunmr** [comment]
will close this issue temporarily. 

If you guys find this issue again, please send more details and feel free to reopen this issue.
